services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodprint-api-api-1
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm run dev
  redis:
    image: redis:6.2-alpine
    container_name: foodprint-api-redis-1
    ports:
      - "6379:6379"
