services:
  api:
    image: ghcr.io/your/repo/foodprint-api:latest
    env_file: .env
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    ports:
      - "80:3000"